version: "3.7"

services:

  mysql:
    ports:
      - '3306:3306'

  proxy:
    ports:
      - 2015:2015
      - 2016:2016
      - 2017:2017

  pma:
    ports:
      - 8090:80

  mail:
    ports:
      - 1025:1025
      - 8025:8025

  nextjs-nexus:
    volumes:
      - ./nextjs-nexus/.storybook:/www/nextjs-nexus/.storybook
      - ./nextjs-nexus/cypress:/www/nextjs-nexus/cypress
      - ./nextjs-nexus/e2e:/www/nextjs-nexus/e2e
      - ./nextjs-nexus/pages:/www/nextjs-nexus/pages
      - ./nextjs-nexus/src:/www/nextjs-nexus/src
      - ./nextjs-nexus/public:/www/nextjs-nexus/public
      - ./nextjs-nexus/stories:/www/nextjs-nexus/stories
      - ./nextjs-nexus/prisma:/www/nextjs-nexus/prisma
      - ./nextjs-nexus/server:/www/nextjs-nexus/server
      - ./nextjs-nexus/package.json:/www/nextjs-nexus/package.json
    command: bash -c "yarn dev"
    ports:
      - 3000:3000

  traders-web:
    volumes:
      - ./traders-web/.storybook:/www/traders-web/.storybook
      - ./traders-web/cypress:/www/traders-web/cypress
      - ./traders-web/e2e:/www/traders-web/e2e
      - ./traders-web/pages:/www/traders-web/pages
      - ./traders-web/src:/www/traders-web/src
      - ./traders-web/public:/www/traders-web/public
      - ./traders-web/stories:/www/traders-web/stories
      - ./traders-web/prisma:/www/traders-web/prisma
      - ./traders-web/server:/www/traders-web/server
      - ./traders-web/package.json:/www/traders-web/package.json
    command: bash -c "yarn dev"
    ports:
      - 3000:3000
